apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:      
      volumes:
        - name: shared-dir1
          persistentVolumeClaim:
            claimName: ping-pong-claim
        - name: shared-dir2
          emptyDir: {}
      containers:
        - name: log-reader
          image: rikusarlin/log-reader:version3
          volumeMounts:
          - name: shared-dir1
            mountPath: /tmp/ping-pong
          - name: shared-dir2
            mountPath: /tmp/timestamp
        - name: timestamp-writer
          image: rikusarlin/timestamp-writer:version3
          volumeMounts:
          - name: shared-dir2
            mountPath: /tmp/timestamp
