apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./todo-app/manifests/deployment.yaml
- ./todo-app/manifests/service_backend.yaml
- ./todo-app/manifests/service_frontend.yaml
- ./todo-app/manifests/ingress.yaml
- ./todo-app/manifests/cronjob.yaml
- ./todo-app/manifests/persistentvolumeclaim.yaml
- ./todo-app/manifests/configmap.yaml
- ./todo-app/manifests/postgresql-service.yaml
- ./todo-app/manifests/postgresql-statefulset.yaml
images:
- name: IMAGE_BACKEND
  newName: rikusarlin/todo-backend:version12
- name: IMAGE_FRONTEND
  newName: rikusarlin/todo-frontend:version12
