apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-claim
spec:
  storageClassName: manual
  volumeName: tempdata-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
