apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-hpa
  namespace: todo-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-app-dep
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50