name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE_FRONTEND: todo-frontend
  IMAGE_BACKEND: todo-backend

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true

    - run: gcloud --quiet auth configure-docker

    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Build backend
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE_BACKEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
          todo-app/todo-backend

    - name: Publish backend
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE_BACKEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

    - name: Build frontend
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
          todo-app/todo-frontend 

    - name: Publish frontend
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Deploy
      run: |-
        kustomize edit set image gcr.io/PROJECT_ID/IMAGE_BACKEND=gcr.io/$PROJECT_ID/$IMAGE_BACKEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
        kustomize edit set image gcr.io/PROJECT_ID/IMAGE_FRONTEND=gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
        kustomize build . | kubectl apply -f -
        kubectl rollout status deployment $IMAGE_BACKEND -n todo-namespace
        kubectl get services -o wide
